backend:
  name: git-gateway
  branch: main

media_folder: "src/content/blog/images"
public_folder: "/content/blog/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, required: true }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: true }
      - { label: "Cover Image", name: "coverImage", widget: "image", required: true }
      - { label: "Tags", name: "tags", widget: "list", default: [], field: { label: "Tag", name: "tag", widget: "string" } }
      - { label: "Video URL", name: "videoUrl", widget: "string", required: false, default: "" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }
